"""add online in technology model

Revision ID: 00d632ce680f
Revises: 3e0918841387
Create Date: 2025-04-10 15:59:02.209198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d632ce680f'
down_revision = '3e0918841387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technologies', sa.Column('online', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_technologies', 'online')
    # ### end Alembic commands ###
