"""empty message

Revision ID: 050f16fb8298
Revises: 00d632ce680f
Create Date: 2025-04-10 16:18:06.045340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050f16fb8298'
down_revision = '00d632ce680f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_technologies', 'online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technologies', sa.Column('online', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
