"""empty message

Revision ID: 062e7e67b45f
Revises: e02b4f35b784
Create Date: 2026-07-02 18:21:27.132387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062e7e67b45f'
down_revision = 'e02b4f35b784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_works', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
