"""change column type for project model

Revision ID: 0bd4c2b48053
Revises: 5b3f895023d1
Create Date: 2025-04-05 00:38:37.709254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd4c2b48053'
down_revision = '5b3f895023d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_projects', 'technologies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_projects', sa.Column('technologies', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
