"""empty message

Revision ID: 14ba5c7d4a3a
Revises: 9bfb0527f4fb
Create Date: 2026-06-26 16:53:00.462916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ba5c7d4a3a'
down_revision = '9bfb0527f4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_customers')
    # ### end Alembic commands ###
