"""empty message

Revision ID: 3c7bca125026
Revises: 050f16fb8298
Create Date: 2025-04-10 16:18:26.745840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7bca125026'
down_revision = '050f16fb8298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technologies', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_technologies', 'online')
    # ### end Alembic commands ###
