"""empty message

Revision ID: 3e0918841387
Revises: 637e4610abf9
Create Date: 2025-04-05 00:44:24.052394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0918841387'
down_revision = '637e4610abf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_projects', sa.Column('year', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_projects', 'year')
    # ### end Alembic commands ###
