"""add temp column in project model

Revision ID: 5b3f895023d1
Revises: 95e3055ee2fe
Create Date: 2025-04-03 18:32:56.009837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3f895023d1'
down_revision = '95e3055ee2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_projects', sa.Column('technologies', sa.Integer(), nullable=True))
    op.alter_column('project_projects', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_projects', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('project_projects', 'technologies')
    # ### end Alembic commands ###
