"""empty message

Revision ID: 637e4610abf9
Revises: 0bd4c2b48053
Create Date: 2025-04-05 00:44:01.643213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637e4610abf9'
down_revision = '0bd4c2b48053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_projects', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_projects', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
