"""empty message

Revision ID: 640b6943b329
Revises: cc5ca6694d74
Create Date: 2026-06-30 17:09:43.680758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640b6943b329'
down_revision = 'cc5ca6694d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cv_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('year_start', sa.SmallInteger(), nullable=True),
    sa.Column('year_end', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('customers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customers_id'], ['project_customers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['cv_positions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_works')
    op.drop_table('cv_positions')
    # ### end Alembic commands ###
