"""add portfolio_technologies

Revision ID: 776c1db6485f
Revises: 0476d5e0d591
Create Date: 2025-03-29 17:43:17.529513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776c1db6485f'
down_revision = '0476d5e0d591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_portfolios_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technologies_id', sa.Integer(), nullable=True),
    sa.Column('portfolios_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolios_id'], ['portfolio_portfolios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technologies_id'], ['portfolio_technologies.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_portfolios', schema=None) as batch_op:
        batch_op.drop_constraint('portfolio_portfolios_activities_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('portfolio_portfolios_functions_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'portfolio_activities', ['activities_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'portfolio_functions', ['functions_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('portfolio_portfolios_functions_id_fkey', 'portfolio_functions', ['functions_id'], ['id'])
        batch_op.create_foreign_key('portfolio_portfolios_activities_id_fkey', 'portfolio_activities', ['activities_id'], ['id'])

    op.drop_table('portfolio_portfolios_technologies')
    # ### end Alembic commands ###
