"""add column meta_description at post model

Revision ID: 81f9c100ba2f
Revises: bc95e9086fea
Create Date: 2025-05-30 17:08:05.053690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f9c100ba2f'
down_revision = 'bc95e9086fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_posts', sa.Column('meta_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles_posts', 'meta_description')
    # ### end Alembic commands ###
