"""empty message

Revision ID: ca25c63cf85e
Revises: 20a87457e044
Create Date: 2025-04-10 16:23:03.354679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca25c63cf85e'
down_revision = '20a87457e044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technologies', sa.Column('online', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_technologies', 'online')
    # ### end Alembic commands ###
