"""empty message

Revision ID: e02b4f35b784
Revises: 4a50bbb3e815
Create Date: 2026-07-01 17:31:23.721319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02b4f35b784'
down_revision = '4a50bbb3e815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_data', sa.Text(), nullable=False))
        batch_op.drop_column('data')

    with op.batch_alter_table('cv_works', schema=None) as batch_op:
        batch_op.alter_column('contract_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_works', schema=None) as batch_op:
        batch_op.alter_column('contract_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cv_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), nullable=False))
        batch_op.drop_column('json_data')

    # ### end Alembic commands ###
