data = {
        "sacla": "fa-regular fa-utensils",
        "cavadeos": "fa-solid fa-horse",
        "banquecasino": "fa-solid fa-piggy-bank",
        "peugeot 4008": "fa-solid fa-car",
        "mypeugeot": "fa-solid fa-car",
        "decolorstop": "fa-solid fa-soap",
        "qui est le moins cher": "fa-solid fa-cart-shopping-fast",
        "michel edouard leclerc": "fa-brands fa-blogger",
        "fidelity vie": "fa-solid fa-money-bill-transfer",
        "algeco": "fa-solid fa-triangle-person-digging",
        "cfcopies": "fa-solid fa-book",
        "air Madagascar": "fa-solid fa-plane",
        "air caraïbes": "fa-solid fa-plane",
        "europcar": "fa-solid fa-car",
        "flyopenskies": "fa-solid fa-plane",
        "areva": "fa-solid fa-radiation",
        "leroy merlin": "fa-solid fa-cart-shopping-fast",
        "peugeot": "fa-solid fa-car",
        "peugeot design lab": "fa-solid fa-car",
        "dyson affaire aireblade": "fa-solid fa-vacuum",
        "brasserie flo": "fa-regular fa-utensils",
        "bazarchic": "fa-solid fa-cart-shopping-fast",
        "mytravelchic": "fa-solid fa-cart-shopping-fast",
        "afflelou": "fa-solid fa-glasses",
        "adp": "fa-solid fa-plane",
        "atelier Renault": "fa-solid fa-car",
        "le siège renault": "fa-solid fa-car",
        "Renault kadjarquest": "fa-solid fa-car",
        "Renault clio RS Melody": "fa-solid fa-car",
        "upsa": "fa-solid fa-notes-medical",
        "system dacia": "fa-solid fa-car",
        "serie toplexil": "fa-solid fa-notes-medical",
        "honda moto": "fa-solid fa-motorcycle",
        "rene furterer": "fa-solid fa-scissors",
        "cevital": "fa-solid fa-shirt",
        "longchamp": "fa-solid fa-shirt",
        "rimowa": "fa-solid fa-shirt",
        "carenity":"fa-solid fa-people-arrows",
        "le point":"fa-solid fa-newspaper",
        "palmares le point":"fa-solid fa-newspaper",
        "radio france": "fa-solid fa-radio",
        "john paul": "fa-thin fa-bell-concierge",
    };