"""empty message

Revision ID: 01de6c313b28
Revises: 1479f2228e40
Create Date: 2022-10-14 22:57:33.496759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01de6c313b28'
down_revision = '1479f2228e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'portfolios', 'activities', ['activities_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_table('activities')
    # ### end Alembic commands ###
