"""empty message

Revision ID: 1479f2228e40
Revises: 47dddbe56a8f
Create Date: 2022-10-14 22:54:58.946568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1479f2228e40'
down_revision = '47dddbe56a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'portfolios', 'activities', ['activities_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.alter_column('portfolios', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
