"""empty message

Revision ID: 27d68eefc3b4
Revises: 9b794ef4c576
Create Date: 2021-09-21 23:12:34.877764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d68eefc3b4'
down_revision = '9b794ef4c576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('color', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'color')
    # ### end Alembic commands ###
