"""empty message

Revision ID: 46cbb6b13687
Revises: 89f7ad4cf5ce
Create Date: 2021-09-23 22:40:04.197192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cbb6b13687'
down_revision = '89f7ad4cf5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('url', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'url')
    # ### end Alembic commands ###
