"""empty message

Revision ID: 47dddbe56a8f
Revises: 549d0800cb66
Create Date: 2022-10-14 22:52:55.111148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dddbe56a8f'
down_revision = '549d0800cb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('portfolios', sa.Column('activities_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'portfolios', 'activities', ['activities_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('portfolios', 'activities_id')
    op.drop_column('portfolios', 'year')
    # ### end Alembic commands ###
