"""empty message

Revision ID: 549d0800cb66
Revises: fcf6b2cce7c8
Create Date: 2022-10-14 22:46:09.152445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549d0800cb66'
down_revision = 'fcf6b2cce7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('portfolios', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('portfolios', sa.Column('activities_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'portfolios', 'activities', ['activities_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('portfolios', 'activities_id')
    op.drop_column('portfolios', 'year')
    op.drop_table('activities')
    # ### end Alembic commands ###
