"""empty message

Revision ID: 89f7ad4cf5ce
Revises: 
Create Date: 2021-09-23 02:07:54.134490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f7ad4cf5ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=8), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('online', sa.SmallInteger(), nullable=True),
    sa.Column('functions_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['functions_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technologies_id', sa.Integer(), nullable=True),
    sa.Column('portfolios_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolios_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['technologies_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios_technologies')
    op.drop_table('portfolios')
    op.drop_table('technologies')
    op.drop_table('functions')
    # ### end Alembic commands ###
