"""empty message

Revision ID: 9b794ef4c576
Revises: e5ed4ae5d7c9
Create Date: 2021-09-21 22:13:17.296908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b794ef4c576'
down_revision = 'e5ed4ae5d7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technologies_id', sa.Integer(), nullable=True),
    sa.Column('portfolios_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolios_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['technologies_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios_technologies')
    op.drop_table('technologies')
    # ### end Alembic commands ###
