"""empty message

Revision ID: ff089d325297
Revises: af756ed86748
Create Date: 2021-09-25 16:59:39.540708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff089d325297'
down_revision = 'af756ed86748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('categories_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'categories', ['categories_id'], ['id'])
    op.drop_column('images', 'thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('thumbnail', sa.SMALLINT(), nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'categories_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
