INSERT INTO project_activities VALUES(1,'aviation','fa-solid fa-plane');
INSERT INTO project_activities VALUES(2,'automobile','fa-solid fa-car');
INSERT INTO project_activities VALUES(3,'sports équestres','fa-solid fa-horse');
INSERT INTO project_activities VALUES(4,'alimentation','fa-solid fa-utensils');
INSERT INTO project_activities VALUES(5,'finance','fa-solid fa-piggy-bank');
INSERT INTO project_activities VALUES(6,'hygiène','fa-solid fa-soap');
INSERT INTO project_activities VALUES(7,'e-commerce','fa-solid fa-cart-shopping');
INSERT INTO project_activities VALUES(8,'blog','fa-brands fa-blogger');
INSERT INTO project_activities VALUES(9,'construction','fa-solid fa-person-digging');
INSERT INTO project_activities VALUES(10,'livres','fa-solid fa-book');
INSERT INTO project_activities VALUES(11,'nucléaire','fa-solid fa-radiation');
INSERT INTO project_activities VALUES(12,'électroménager','fa-solid fa-blender-phone');
INSERT INTO project_activities VALUES(13,'opticien','fa-solid fa-glasses');
INSERT INTO project_activities VALUES(14,'santé','fa-solid fa-notes-medical');
INSERT INTO project_activities VALUES(15,'motocyclette','fa-solid fa-motorcycle');
INSERT INTO project_activities VALUES(16,'coiffure','fa-solid fa-scissors');
INSERT INTO project_activities VALUES(17,'grande distibution','fa-solid fa-shirt');
INSERT INTO project_activities VALUES(18,'bagage','fa-solid fa-suitcase-rolling');
INSERT INTO project_activities VALUES(19,'réseau social','fa-solid fa-people-arrows');
INSERT INTO project_activities VALUES(20,'journalisme','fa-solid fa-newspaper');
INSERT INTO project_activities VALUES(21,'la radio','fa-solid fa-radio');
INSERT INTO project_activities VALUES(22,'conciergerie','fa-solid fa-bell-concierge');
INSERT INTO project_activities VALUES(23,'maroquinerie','bla');
INSERT INTO project_activities VALUES(24,'musique','fa-solid fa-music');
